import {Component, OnInit} from '@angular/core';

@Component({selector: 'app-vendors-list', templateUrl: './vendors-list.component.html', styleUrls: ['./vendors-list.component.css']})
export class VendorsListComponent implements OnInit {
    vendors = [
        {
            "id": 1,
            "name": "Derward",
            "address": "Habben",
            "phone": "175-891-5268",
            "website": "https://godaddy.com/",
            "contactName": "Podcat",
            "contactEmail": "dhabben0@rediff.com",
            "date": "7/28/2020"
        }, {
            "id": 2,
            "name": "Jeffry",
            "address": "Klaesson",
            "phone": "898-131-7831",
            "website": "http://elpais.com",
            "contactName": "Realcube",
            "contactEmail": "jklaesson1@topsy.com",
            "date": "6/13/2020"
        }, {
            "id": 3,
            "name": "Huntlee",
            "address": "Extall",
            "phone": "756-107-0391",
            "website": "http://twitter.com",
            "contactName": "Babbleblab",
            "contactEmail": "hextall2@simplemachines.org",
            "date": "10/18/2020"
        }, {
            "id": 4,
            "name": "Bel",
            "address": "Quixley",
            "phone": "455-637-8479",
            "website": "http://wired.com",
            "contactName": "Skajo",
            "contactEmail": "bquixley3@opera.com",
            "date": "8/6/2020"
        }, {
            "id": 5,
            "name": "Sawyere",
            "address": "Cornfield",
            "phone": "595-651-2309",
            "website": "http://typepad.com",
            "contactName": "Mudo",
            "contactEmail": "scornfield4@forbes.com",
            "date": "2/11/2020"
        }, {
            "id": 6,
            "name": "Clementine",
            "address": "Gasticke",
            "phone": "722-855-4599",
            "website": "https://tinyurl.com/",
            "contactName": "Browsebug",
            "contactEmail": "cgasticke5@a8.net",
            "date": "4/6/2020"
        }, {
            "id": 7,
            "name": "Millie",
            "address": "McAuslan",
            "phone": "725-672-2359",
            "website": "http://posterous.com/",
            "contactName": "Voonyx",
            "contactEmail": "mmcauslan6@shareasale.com",
            "date": "12/28/2020"
        }, {
            "id": 8,
            "name": "Nicko",
            "address": "Hawkridge",
            "phone": "272-328-9139",
            "website": "https://tripod.com/",
            "contactName": "Skyba",
            "contactEmail": "nhawkridge7@google.com.hk",
            "date": "4/29/2020"
        }, {
            "id": 9,
            "name": "Abran",
            "address": "Peake",
            "phone": "152-923-5599",
            "website": "http://vistaprint.com",
            "contactName": "Thoughtbeat",
            "contactEmail": "apeake8@feedburner.com",
            "date": "12/19/2020"
        }, {
            "id": 10,
            "name": "Regen",
            "address": "Eliyahu",
            "phone": "138-893-5104",
            "website": "http://yellowpages.com/",
            "contactName": "Meezzy",
            "contactEmail": "reliyahu9@gnu.org",
            "date": "6/24/2020"
        }, {
            "id": 11,
            "name": "Korrie",
            "address": "Guerola",
            "phone": "827-892-6781",
            "website": "http://cloudflare.com/",
            "contactName": "Thoughtworks",
            "contactEmail": "kguerolaa@usatoday.com",
            "date": "10/28/2020"
        }, {
            "id": 12,
            "name": "Granville",
            "address": "Colloby",
            "phone": "640-949-7970",
            "website": "http://comcast.net/r",
            "contactName": "Edgewire",
            "contactEmail": "gcollobyb@blogs.com",
            "date": "10/16/2020"
        }, {
            "id": 13,
            "name": "Ninon",
            "address": "Cluley",
            "phone": "128-824-0985",
            "website": "http://mashable.com/u",
            "contactName": "Riffwire",
            "contactEmail": "ncluleyc@nymag.com",
            "date": "2/16/2020"
        }, {
            "id": 14,
            "name": "Rosabelle",
            "address": "Ulyat",
            "phone": "578-742-2722",
            "website": "http://toplist.cz/",
            "contactName": "Rhyloo",
            "contactEmail": "rulyatd@home.pl",
            "date": "12/15/2020"
        }, {
            "id": 15,
            "name": "Denis",
            "address": "Sarfati",
            "phone": "612-154-0335",
            "website": "http://va.gov/purus",
            "contactName": "Thoughtsphere",
            "contactEmail": "dsarfatie@tinypic.com",
            "date": "8/21/2020"
        }, {
            "id": 16,
            "name": "Aili",
            "address": "Helbeck",
            "phone": "915-477-6903",
            "website": "http://amazonaws.com",
            "contactName": "Jayo",
            "contactEmail": "ahelbeckf@usda.gov",
            "date": "2/11/2020"
        }, {
            "id": 17,
            "name": "Charlotte",
            "address": "Kordas",
            "phone": "106-650-3758",
            "website": "https://booking.com",
            "contactName": "Mymm",
            "contactEmail": "ckordasg@wufoo.com",
            "date": "2/9/2020"
        }, {
            "id": 18,
            "name": "Arabelle",
            "address": "Toffolo",
            "phone": "810-147-3513",
            "website": "https://theglobeandmail." +
                    "aucibus&porta=cursus",
            "contactName": "Mymm",
            "contactEmail": "atoffoloh@census.gov",
            "date": "2/9/2020"
        }, {
            "id": 19,
            "name": "Bevin",
            "address": "Penniell",
            "phone": "915-442-3577",
            "website": "https://theglobeandmail.com/in/" +
                    "&id=erat",
            "contactName": "Wordtune",
            "contactEmail": "bpennielli@google.ru",
            "date": "8/24/2020"
        }, {
            "id": 20,
            "name": "Lark",
            "address": "Riepel",
            "phone": "821-752-5951",
            "website": "http://hp.com/turpis/adipisc",
            "contactName": "Wordware",
            "contactEmail": "lriepelj@sakura.ne.jp",
            "date": "7/10/2020"
        }, {
            "id": 21,
            "name": "Sheridan",
            "address": "Deneve",
            "phone": "577-421-2165",
            "website": "http://soundcloud.com/placerat/",
            "contactName": "Riffwire",
            "contactEmail": "sdenevek@msn.com",
            "date": "11/17/2020"
        }, {
            "id": 22,
            "name": "Lewie",
            "address": "Varcoe",
            "phone": "604-833-5176",
            "website": "https://miitbeian.gov.cn/sapien/" +
                    "nisi",
            "contactName": "Jaxnation",
            "contactEmail": "lvarcoel@homestead.com",
            "date": "5/14/2020"
        }, {
            "id": 23,
            "name": "Kenn",
            "address": "Scading",
            "phone": "378-737-7481",
            "website": "http://mail.ru/justo.aspx?pellentes",
            "contactName": "Aivee",
            "contactEmail": "kscadingm@google.it",
            "date": "8/22/2020"
        }, {
            "id": 24,
            "name": "Buffy",
            "address": "Greader",
            "phone": "482-994-9641",
            "website": "https://w3.org/habitas" +
                    "ltrices",
            "contactName": "Yamia",
            "contactEmail": "bgreadern@loc.gov",
            "date": "7/10/2020"
        }, {
            "id": 25,
            "name": "Rozanna",
            "address": "Bowne",
            "phone": "706-935-7265",
            "website": "https://mozilla.com",
            "contactName": "Meembee",
            "contactEmail": "rbowneo@issuu.com",
            "date": "11/4/2020"
        }
    ]
    constructor() {}

    ngOnInit() {}

}
