import {Component, EventEmitter, OnInit, Output} from '@angular/core';

@Component({selector: 'app-insurance-list', templateUrl: './insurance-list.component.html', styleUrls: ['./insurance-list.component.scss']})
export class InsuranceListComponent implements OnInit {
    @Output()view = new EventEmitter()
    issues = [
        {
            "id": 1,
            "name": "Derek",
            "temp": 37,
            "pulse": 138,
            "oxygen": 61,
            "date": "3/22/2021"
        }, {
            "id": 2,
            "name": "Tabbitha",
            "temp": 37,
            "pulse": 129,
            "oxygen": 99,
            "date": "3/2/2021"
        }, {
            "id": 3,
            "name": "Ethe",
            "temp": 40,
            "pulse": 93,
            "oxygen": 51,
            "date": "4/22/2021"
        }, {
            "id": 4,
            "name": "Maitilde",
            "temp": 40,
            "pulse": 80,
            "oxygen": 69,
            "date": "5/6/2021"
        }, {
            "id": 5,
            "name": "Caralie",
            "temp": 39,
            "pulse": 115,
            "oxygen": 57,
            "date": "2/20/2021"
        }, {
            "id": 6,
            "name": "Roxanna",
            "temp": 38,
            "pulse": 95,
            "oxygen": 83,
            "date": "4/11/2021"
        }, {
            "id": 7,
            "name": "Jocko",
            "temp": 35,
            "pulse": 118,
            "oxygen": 58,
            "date": "2/16/2021"
        }, {
            "id": 8,
            "name": "Grier",
            "temp": 39,
            "pulse": 168,
            "oxygen": 52,
            "date": "4/21/2021"
        }, {
            "id": 9,
            "name": "Ebonee",
            "temp": 39,
            "pulse": 115,
            "oxygen": 45,
            "date": "4/29/2021"
        }, {
            "id": 10,
            "name": "Lynnet",
            "temp": 38,
            "pulse": 214,
            "oxygen": 73,
            "date": "4/17/2021"
        }, {
            "id": 11,
            "name": "Richard",
            "temp": 38,
            "pulse": 215,
            "oxygen": 81,
            "date": "5/5/2021"
        }, {
            "id": 12,
            "name": "Mart",
            "temp": 38,
            "pulse": 128,
            "oxygen": 75,
            "date": "4/6/2021"
        }, {
            "id": 13,
            "name": "Mattheus",
            "temp": 38,
            "pulse": 150,
            "oxygen": 82,
            "date": "3/25/2021"
        }, {
            "id": 14,
            "name": "Ricca",
            "temp": 40,
            "pulse": 190,
            "oxygen": 70,
            "date": "4/13/2021"
        }, {
            "id": 15,
            "name": "Tobin",
            "temp": 37,
            "pulse": 74,
            "oxygen": 74,
            "date": "5/2/2021"
        }, {
            "id": 16,
            "name": "Robin",
            "temp": 39,
            "pulse": 181,
            "oxygen": 92,
            "date": "4/25/2021"
        }, {
            "id": 17,
            "name": "Janetta",
            "temp": 37,
            "pulse": 144,
            "oxygen": 69,
            "date": "3/4/2021"
        }, {
            "id": 18,
            "name": "Vikki",
            "temp": 32,
            "pulse": 122,
            "oxygen": 52,
            "date": "4/18/2021"
        }, {
            "id": 19,
            "name": "Emmey",
            "temp": 35,
            "pulse": 81,
            "oxygen": 60,
            "date": "3/24/2021"
        }, {
            "id": 20,
            "name": "Fritz",
            "temp": 39,
            "pulse": 205,
            "oxygen": 43,
            "date": "3/18/2021"
        }, {
            "id": 21,
            "name": "Yard",
            "temp": 39,
            "pulse": 65,
            "oxygen": 67,
            "date": "4/28/2021"
        }, {
            "id": 22,
            "name": "Cati",
            "temp": 36,
            "pulse": 132,
            "oxygen": 77,
            "date": "3/23/2021"
        }, {
            "id": 23,
            "name": "Opalina",
            "temp": 39,
            "pulse": 84,
            "oxygen": 76,
            "date": "3/30/2021"
        }, {
            "id": 24,
            "name": "Constantine",
            "temp": 38,
            "pulse": 71,
            "oxygen": 57,
            "date": "3/12/2021"
        }, {
            "id": 25,
            "name": "Hertha",
            "temp": 39,
            "pulse": 211,
            "oxygen": 82,
            "date": "5/9/2021"
        }
    ]
    constructor() {}

    ngOnInit() {}

}
